### ISSUE TITLE
LED flashlight

### ISSUE THREAD

**Issue by Damiano1997** [ArchiDroid/android_device_samsung_i9300#13]
When screen turns off, the flashlight turns off too. When the screen goes on, the flashlight icon in the notification bar is marked as turned on. When clicked, the icon disappear for a few seconds.

**Comment by MarcKe** [comment]
Not a device issue. The problem is that the Torch app in cm11 used a simple sysfs toggle for our device. If you click the tile in the notification drawer in cm12, it uses the camera interface, etc. Our device does not like that, but nothing to fix here for us.
If you enable the flashlight like this: echo 10 > /sys/class/camera/rear/rear_flash
everything will be fine.

**Comment by MarcKe** [comment]
Also works now in latest version, seems to have been fixed from cm side.

**Comment by DimitriMayakovsky** [comment]
MarcKe look this 

# Torch
    chown system system /sys/class/camera/rear/rear_flash
    chmod 0667 /sys/class/camera/rear/rear_flash

**Comment by MarcKe** [comment]
What is this supposed to change?
Why do you add the execute bit to the "others" permission. The file wont be executed, just written to.
And changing the group ownership also wont change anything, since all of them have read and write permissions (6).
I also tested it and it does not change anything.
