### ISSUE TITLE
Mobile Data Connection Lost

### ISSUE THREAD

**Issue by DineshPatil3** [ArchiDroid/android_device_samsung_i9300#97]
I've noticed one bug, where my Mobile Data Connection is on and still my internet doesn't work. I've tried all the possibilities. But the mobile data connection is restored only after rebooting the cell.

**Comment by danielps1** [comment]
I've noticed the same. When I go into the settings for mobile connections "com.android.phone" crashes

**Comment by walsl** [comment]
I've noticed same bug.

**Comment by Marlamin** [comment]
Can confirm as of Weekly 5. I can not get a data connection whatsoever. Mobile network icon constantly has a ! next to it. Not that much of an issue for me since I'm almost always on Wi-Fi but I'm sure this could be annoying to someone. 

This is everything I found in logcat that's RIL related. Not sure if it's any help since it only meantions gps(?).

`
05-15 09:18:50.450: D/libgps(2403): agps_ril_update_network_state: Waiting for IPC connection...
05-15 09:18:51.475: D/libgps(2403): agps_ril_update_network_state: Waiting for IPC connection - timeout
05-15 09:18:51.480: E/libgps(2403): IPC Communication Error, /tmp/12813836_188397/proprietary/deliverables/android/gps_interface/../gps_interface/gpsi_client/GpsiClient.cpp:1143 agps_ril_update_network_state
05-15 09:18:51.480: D/libgps(2403): proxy_agps_ril_update_network_state: called
05-15 09:18:51.480: D/libgps(2403): agps_ril_update_network_availability: Waiting for IPC connection...
05-15 09:18:52.505: D/libgps(2403): agps_ril_update_network_availability: Waiting for IPC connection - timeout
05-15 09:18:52.505: E/libgps(2403): IPC Communication Error, /tmp/12813836_188397/proprietary/deliverables/android/gps_interface/../gps_interface/gpsi_client/GpsiClient.cpp:1161 agps_ril_update_network_availability
05-15 09:20:19.130: D/libgps(2403): agps_ril_update_network_state: Waiting for IPC connection...
05-15 09:20:20.155: D/libgps(2403): agps_ril_update_network_state: Waiting for IPC connection - timeout
05-15 09:20:20.155: E/libgps(2403): IPC Communication Error, /tmp/12813836_188397/proprietary/deliverables/android/gps_interface/../gps_interface/gpsi_client/GpsiClient.cpp:1143 agps_ril_update_network_state
05-15 09:20:20.155: D/libgps(2403): proxy_agps_ril_update_network_state: called
05-15 09:20:20.155: D/libgps(2403): agps_ril_update_network_availability: Waiting for IPC connection...
05-15 09:20:21.160: D/libgps(2403): agps_ril_update_network_availability: Waiting for IPC connection - timeout
05-15 09:20:21.160: E/libgps(2403): IPC Communication Error, /tmp/12813836_188397/proprietary/deliverables/android/gps_interface/../gps_interface/gpsi_client/GpsiClient.cpp:1161 agps_ril_update_network_availability
05-15 09:20:21.160: D/libgps(2403): agps_ril_update_network_state: Waiting for IPC connection...
05-15 09:20:22.175: D/libgps(2403): agps_ril_update_network_state: Waiting for IPC connection - timeout
05-15 09:20:22.175: E/libgps(2403): IPC Communication Error, /tmp/12813836_188397/proprietary/deliverables/android/gps_interface/../gps_interface/gpsi_client/GpsiClient.cpp:1143 agps_ril_update_network_state
05-15 09:20:22.175: D/libgps(2403): proxy_agps_ril_update_network_state: called
05-15 09:20:22.175: D/libgps(2403): agps_ril_update_network_availability: Waiting for IPC connection...
05-15 09:20:23.180: D/libgps(2403): agps_ril_update_network_availability: Waiting for IPC connection - timeout
05-15 09:20:23.180: E/libgps(2403): IPC Communication Error, /tmp/12813836_188397/proprietary/deliverables/android/gps_interface/../gps_interface/gpsi_client/GpsiClient.cpp:1161 agps_ril_update_network_availability
`

**Comment by Ciberajj** [comment]
Can confirm the problem. Sometimes the data connection is lost and doesn't untill reboot the device. Sometimes comes back when activating and de-activating fly mode.

**Comment by tchaker** [comment]
there is an other problem. i can't create a new APN. it doesn't work.

**Comment by bignig473** [comment]
Put it on Airplane Mode to get to configure the APN settings

**Comment by boner** [comment]
Hi, I have the same problem with network. Yesterday I have installed last version - build 9 , and there is still the same network problem. If I lost connection, I have to restart mobile to get hsdpa+ again :/

**Comment by ksfga** [comment]
I experience the same issue. There is an exclamation mark in signal strength icon.

**Comment by boner** [comment]
My little update - after few days it works fine for me. I dont have any connection losts or problem with signal strength - maybe it needed few days to fit in?

**Comment by ibhh** [comment]
Using it for more than two weeks now. Connection losts occure 2-10 times a day.

**Comment by JustArchi** [comment]
Tried to reproduce it several times and simply couldn't, mobile data works perfectly fine. Therefore I blame either modem, local network, or CM's network routes.

Not going to be considered in any of these cases.
